### ISSUE TITLE
match issue

### ISSUE THREAD

**Issue by j2l** [oimoyu/simple-comfyui-texture#1]
Hello,
Simple but effective add-on, and working on Linux! Congrats for this gem and thank you!

I just have a small issue with "Match Brush", it doesn't match, even after multiple trials (see the gray area on top face?):
![image](https://github.com/oimoyu/simple-comfyui-texture/assets/65325/e9b3b6a4-3933-4e06-a924-6dad29d0a0bd)

Whatever the perspective, there's a small shift between camera view and texture paint mask:
![image](https://github.com/oimoyu/simple-comfyui-texture/assets/65325/aa7404dc-54e0-4950-97d1-84429ae7bde3)
I'm using Blender 4.0.2

Any idea?

**Comment by oimoyu** [comment]
fixed
